name: CI

on: [push, pull_request]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v1
    - name: Setup paths
      run: |
        mkdir -p $HOME/.local/bin
        mkdir -p $HOME/.local/lib/pkgconfig
        export PKG_CONFIG_PATH=$HOME/.local/lib/pkgconfig:$PKG_CONFIG_PATH
        export LD_LIBRARY_PATH=$HOME/.local/lib:$LD_LIBRARY_PATH
        export PATH=$HOME/.local/bin:$PATH
        export NUM_CPUS=`nproc --all`
    - name: Install boost
      run: |
        export BOOST=1_66_0
        pushd ~
        for i in {1..5}; do
          wget -T20 -t1 -O "boost_${BOOST}.tar.bz2" "https://github.com/pcb2gcode/pcb2gcode/releases/download/v2.0.0/boost_${BOOST}.tar.bz2" && break;
        done
        tar xjf "boost_${BOOST}.tar.bz2"
        pushd boost_${BOOST}
        export BOOST_DIR="$HOME/boost"
        ./bootstrap.sh --with-libraries=program_options --prefix=${BOOST_DIR}
        ./b2
        ./b2 install
        popd
        popd
    - name: Install gerbv
      run: |
        pushd ~
        git clone https://github.com/eyal0/gerbv.git
        pushd gerbv
        sh autogen.sh
        ./configure CPPFLAGS=$CPPFLAGS_gerbv --disable-update-desktop-database --prefix=${HOME}/.local
        make -j ${NUM_CPUS}
        make install
        popd
        popd
    - name: Pip install coverage libraries
      run: |
        pip install --user cpp-coveralls colour_runner unittest2 termcolor concurrencytest in_place
    - name: Install valgrind
      run: |
        pushd ~
        git clone git://sourceware.org/git/valgrind.git
        pushd valgrind
        sh autogen.sh
        ./configure --prefix=${HOME}/.local
        make -j 2
        make install
        popd
        popd
