name: CI

on: [push, pull_request]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - name: Display env
      run: env
    - uses: actions/checkout@v1
    - name: Setup paths
      run: |
        mkdir -p $HOME/.local/bin
        mkdir -p $HOME/.local/lib/pkgconfig
        echo "::set-env name=PKG_CONFIG_PATH=$(echo $HOME/.local/lib/pkgconfig:$PKG_CONFIG_PATH)"
        echo "::set-env name=LD_LIBRARY_PATH=$(echo $HOME/.local/lib:$LD_LIBRARY_PATH)"
        echo "::set-env name=PATH::$(echo $HOME/.local/bin:$PATH)"
        echo "::set-env name=NUM_CPUS::$(nproc --all)"
    - name: apt-get chronic
      run: |
        sudo apt-get install moreutils
    - name: Install boost
      run: |
        export BOOST=1_66_0
        pushd ~
        for i in {1..5}; do
          wget -T20 -t1 -O "boost_${BOOST}.tar.bz2" "https://github.com/pcb2gcode/pcb2gcode/releases/download/v2.0.0/boost_${BOOST}.tar.bz2" && break;
        done
        tar xjf "boost_${BOOST}.tar.bz2"
        pushd boost_${BOOST}
        ./bootstrap.sh --with-libraries=program_options --prefix=${HOME}/.local
        ./b2 -j ${NUM_CPUS}
        ./b2 install
        popd
        popd
    - name: Install gerbv
      run: |
        sudo apt-get install autopoint
        sudo apt-get install libgtkmm-2.4-dev
        pushd ~
        git clone https://github.com/eyal0/gerbv.git
        pushd gerbv
        sh autogen.sh
        ./configure CPPFLAGS=$CPPFLAGS_gerbv --disable-update-desktop-database --prefix=${HOME}/.local
        make -j ${NUM_CPUS}
        make install
        popd
        popd
    - name: Pip install coverage libraries
      run: |
        pip install --user cpp-coveralls colour_runner unittest2 termcolor concurrencytest in_place
    - name: Install valgrind
      run: |
        pushd ~
        git clone git://sourceware.org/git/valgrind.git
        pushd valgrind
        sh autogen.sh
        ./configure --prefix=${HOME}/.local
        make -j 2
        make install
        popd
        popd
    - name: Install parallel
      run: |
        pushd ~
        for i in {1..5}; do
          wget -T5 -t1 -O "parallel-latest.tar.bz2" "http://ftpmirror.gnu.org/parallel/parallel-latest.tar.bz2" && break;
        done
        mkdir parallel
        pushd parallel
        tar xjf "../parallel-latest.tar.bz2"
        pushd parallel-*
        ./configure --prefix=${HOME}/.local
        make
        make install
        popd
        popd
        popd
    - name: Finalize setup
      run: |
        hash -r
    - name: pcb2gcode autoreconf
      run: autoreconf -fvi
    - name: pcb2gcode configure
      run: >-
        ./configure pcb2gcode_CPPFLAGS_EXTRA=-Werror
        --disable-dependency-tracking
        --disable-silent-rules
        --enable-static-boost
        || cat config.log
    - name: pcb2gcode make
      run: make -j ${NUM_CPUS}
