name: CI

on: [push, pull_request]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v1
    - name: Setup paths
      run: |
        mkdir -p $HOME/.local/bin
        mkdir -p $HOME/.local/lib/pkgconfig
        export PKG_CONFIG_PATH=$HOME/.local/lib/pkgconfig:$PKG_CONFIG_PATH
        export LD_LIBRARY_PATH=$HOME/.local/lib:$LD_LIBRARY_PATH
        export PATH=$HOME/.local/bin:$PATH
        export NUM_CPUS=`nproc --all`
    - name: apt-get chronic
      run: |
        sudo apt-get install moreutils
    - name: Install boost
      run: |
        export BOOST=1_66_0
        pushd ~
        for i in {1..5}; do
          wget -T20 -t1 -O "boost_${BOOST}.tar.bz2" "https://github.com/pcb2gcode/pcb2gcode/releases/download/v2.0.0/boost_${BOOST}.tar.bz2" && break;
        done
        tar xjf "boost_${BOOST}.tar.bz2"
        pushd boost_${BOOST}
        export BOOST_DIR="$HOME/boost"
        chronic ./bootstrap.sh --with-libraries=program_options --prefix=${BOOST_DIR}
        chronic ./b2
        chronic ./b2 install
        popd
        popd
    - name: Install gerbv
      run: |
        sudo apt-get install autopoint
        sudo apt-get install libgtkmm-2.4-dev
        pushd ~
        git clone https://github.com/eyal0/gerbv.git
        pushd gerbv
        chronic sh autogen.sh
        chronic ./configure CPPFLAGS=$CPPFLAGS_gerbv --disable-update-desktop-database --prefix=${HOME}/.local
        chronic make -j ${NUM_CPUS}
        chronic make install
        popd
        popd
    - name: Pip install coverage libraries
      run: |
        pip install --user cpp-coveralls colour_runner unittest2 termcolor concurrencytest in_place
    - name: Install valgrind
      run: |
        pushd ~
        git clone git://sourceware.org/git/valgrind.git
        pushd valgrind
        chronic sh autogen.sh
        chronic ./configure --prefix=${HOME}/.local
        chronic make -j 2
        chronic make install
        popd
        popd
    - name: Install parallel
      run: |
        pushd ~
        for i in {1..5}; do
          wget -T5 -t1 -O "parallel-latest.tar.bz2" "http://ftpmirror.gnu.org/parallel/parallel-latest.tar.bz2" && break;
        done
        mkdir parallel
        pushd parallel
        tar xjf "../parallel-latest.tar.bz2"
        pushd parallel-*
        chronic ./configure --prefix=${HOME}/.local
        chronic make
        chronic make install
        popd
        popd
        popd
    - name: Finalize setup
      run: |
        hash -r
    - name: pcb2gcode autoreconf
      run: autoreconf -fvi
    - name: pcb2gcode configure
      run: ./configure pcb2gcode_CPPFLAGS_EXTRA=-Werror --disable-dependency-tracking --disable-silent-rules --with-boost="$BOOST_DIR"
    - name: pcb2gcode make
      run: make -j ${NUM_CPUS}
